### ISSUE TITLE
Does not support Google Maps v2

### ISSUE THREAD

**Issue by LeVadim** [jasonmamy/cordova-wheel-selector-plugin#12]
cordova information: (run $> cordova plugin list)
com.googlemaps.ios 2.3.0 "Google Maps SDK for iOS"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-googlemaps 2.0.0-beta3-20170816-1600 "cordova-plugin-googlemaps"
cordova-plugin-wkwebview-engine 1.1.4-dev "Cordova WKWebView Engine"
cordova-wheel-selector-plugin 1.0.0 "Cordova Wheel Selector Plugin"

Current behavior:
https://ionicframework.com/docs/native/wheelselector-plugin/
https://ionicframework.com/docs/native/date-picker/
These both 2 plugins does not work at all with new Google Maps version.
The feeling is that those 2 plugins are invisible - finger can't do any tap.

Expected behavior:
They should work as they worked in the 1.4 version.

https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1650

**Comment by jasonmamy** [comment]
Do you have an example code snippet I could try, so could reproduce the
issue?  Are you using the latest version of the wheel selector plugin
(1.0.9)?

**Comment by LeVadim** [comment]
It seems I was using old version - cordova-wheel-selector-plugin 1.0.0 "Cordova Wheel Selector Plugin"
Will run an example and will let you know shortly.
Thanks!

**Comment by d3vtoolsmith** [comment]
I've confirmed in my project that this is indeed an issue..Uninstalling google maps plugin (https://ionicframework.com/docs/native/google-maps/) did resolve the issue, and thankfully we're able to use Google JS SDK for mapping for now.
I'll try to create and upload a simple project showing this.

**Comment by z1ad** [comment]
Same issue here.. the wheel selector appears but you cannot tap/interact with it, almost as if its invisible.
Simply uninstalling the mapsplugin solves the problem but unfortunately I need them both in my project.

Any ideas what might be causing this? It only affects iOS. Confirmed on both iOS 9 and 10 if that helps.

Edit: it also affects another similar plugin: PhoneGap-Plugin-ListPicker-2.2.2

**Comment by jasonmamy** [comment]
I'm not sure as I don't have access to a Mac or IOS anymore, is there
anyone that could take a look?  Are there any interesting things in the
logs or output on IOS?

**Comment by z1ad** [comment]
I think this should fix the issue, I have tested against a similar plugin but havent had a chance to confirm with wheel selector plugin yet.

https://github.com/mapsplugin/cordova-plugin-googlemaps/pull/1875
