### ISSUE TITLE
Not able to install plugin.

### ISSUE THREAD

**Issue by bimal72** [jasonmamy/cordova-wheel-selector-plugin#13]
Hello, 
My environment is

cli packages: (f:\projects\plenar\doctodoor\ionic_project\d2d_ionic\node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.0.2
    Cordova Platforms  : android 6.1.2
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v6.11.0
    npm  : 3.10.10
    OS   : Windows 8.1

When I run the command : 
cordova plugin add cordova-wheel-selector-plugin --save

It throws error
```
> cordova plugin add cordova-wheel-selector-plugin --save
x Running command - failed!
[ERROR] An error occurred while running cordova plugin add cordova-wheel-selector-plugin --save (exit code 1):


        Error: Cannot find plugin.xml for plugin "cordova-wheel-selector-plugin". Please try adding it again.

```

**Comment by jasonmamy** [comment]
Not sure if it's a dependency issue but I created a temp ionic2 project and ran the command and it worked:

```
$ cordova plugin add cordova-wheel-selector-plugin --save
Adding cordova-wheel-selector-plugin to package.json
Saved plugin info for "cordova-wheel-selector-plugin" to config.xml
```

The latest version of ionic:


```
$ ionic info
cli packages: (/usr/local/share/node-v6.11.1-linux-x64/lib/node_modules)
    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

local packages:
    @ionic/app-scripts : 2.1.4
    Ionic Framework    : ionic-angular 3.6.0

System:
    Node : v6.11.1
    npm  : 3.10.10 
    OS   : Linux 4.10
```

Since the wheel selector isn't released (yet) in ionic-native you also have to follow these instructions:

https://github.com/jasonmamy/cordova-wheel-selector-plugin#for-ionic-2

**Comment by nicks258** [comment]
Still getting `Error: Failed to fetch plugin cordova-wheel-selector-plugin@^1.0.1 via registry.` also I followed https://github.com/jasonmamy/cordova-wheel-selector-plugin#for-ionic-2 steps it says Install the WheelSelector plugin: 'ionic cordova plugin add cordova-wheel-selector-plugin' but getting same error running that. please help

**Comment by jasonmamy** [comment]
Try these steps, I just ran on my machine and everything worked:


ionic start MyIonicProject tutorial
cd MyIonicProject
ionic cordova plugin add cordova-wheel-selector-plugin
npm install --save @ionic-native/wheel-selector


my ionic info is:

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:
    cordova (Cordova CLI) : 8.0.0

local packages:
    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:
    Android SDK Tools : 26.1.1
    Node              : v8.9.4
    npm               : 5.6.0
    OS                : Linux 4.13

Environment Variables:
    ANDROID_HOME : /home/xxx/apps/android-sdk

Misc:
    backend : pro
