### ISSUE TITLE
6 items wheel selector 

### ISSUE THREAD

**Issue by ekaradev** [jasonmamy/cordova-wheel-selector-plugin#14]
https://i.hizliresim.com/RPaRX7.jpg

How can i do that  3 top and 3 bottom

**Comment by jasonmamy** [comment]
It currently doesn't support 'splitting' the row into multiple columns.

**Comment by ekaradev** [comment]
@jasonmamy Thank you ,  Will it support in future releases?

**Comment by jasonmamy** [comment]
Yes, I will try to add it in a future release.
