### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by kotromeo** [jasonmamy/cordova-wheel-selector-plugin#17]
![jasonmamy-cordova-wheel-selector-plugin- wheel selector for cordova android-ios 2017-12-01 10-31-29](https://user-images.githubusercontent.com/6111034/33472347-e74153aa-d682-11e7-9e4f-85cadba35d9f.png)

**Comment by kotromeo** [comment]
One more issue

![jasonmamy-cordova-wheel-selector-plugin- wheel selector for cordova android-ios 2017-12-01 10-38-43](https://user-images.githubusercontent.com/6111034/33472562-ef4ee8cc-d683-11e7-9646-32abfdc21c77.png)

**Comment by jasonmamy** [comment]
Thanks for the heads up - fixed.
