### ISSUE TITLE
Colors on Android 4.x and 5

### ISSUE THREAD

**Issue by hohae** [jasonmamy/cordova-wheel-selector-plugin#20]
I'm using the "light" theme. It works perfectly on Android 6 and higher. But on Android 4 and 5 I get strange renderings: Black font on black background or at least a very low contrast. Any hints?

THX,
Holger

**Comment by jasonmamy** [comment]
I don't have access to Android 4/5, but it's gotta be close to these lines
of code:

https://github.com/jasonmamy/cordova-wheel-selector-plugin/blob/master/src/android/com/wellseek/cordova/SelectorCordovaPlugin.java#L216

Try messing with that and see if it makes a difference?  I know it wasn't
easy to change those colors in code (they wanted you to do it in android
manifest which really doesn't easily exist in ionic), so it's kinda hacky
in there.

**Comment by hohae** [comment]
Jason,

I’ve found the problem. The theme you’re using has been introduced in Android 5.1. For versions before 5.1, it falls back to default themes. Those two changes fix the behavior in all Android versions.

[cid:image002.png@01D3A963.A081BD70]


[cid:image001.png@01D3A963.30C1F3B0]

I’ve also been facing some problems with JS code in selectorplugin.js in the context of a Cordova app. I had to change the following lines:

[cid:image003.png@01D3A964.0BE44790]

Do you want to integrate that code into your code? Or should I run this in my own copy of your plugin?

Regards,
Holger

**Comment by jasonmamy** [comment]
If you can do a pull request with the changes then I can merge them into
the main branch and spin off another release, that would be the easiest.

**Comment by okaufmann** [comment]
I have the same Problem but am not a Java developer. Any tips how to fix this (then I would give it a try 🙈)

Here is a Example how it looks now:
![image](https://user-images.githubusercontent.com/4414498/37080744-89999482-21e7-11e8-83be-61b6e3cc6bdf.png)

**Comment by jb280** [comment]
Did Holger's fix for older android versions get integrated in?  (or posted in a readable form)? I'm guessing the images he posted in his email didn't make it here? (ie. [cid:image002.png@01D3A963.A081BD70]).  I'm seeing the black selector & text on older android phones. Thanks.

**Comment by jasonmamy** [comment]
No, he never did a pull request, so there was nothing to merge back in?
Holger, can you add a pull request with your changes so we can push it back
into the main code line?  Thanks!

**Comment by hohae** [comment]
I have to do some cleanup in my code first before adding a PR. There were more problems in Android regarding font sizes of the button and title label and the selected and non-selected items. I’ve just done quick and dirty fixes for my app.

**Comment by conormag** [comment]
@jasonmamy any way you can post the images @hohae sent? really need to know that fix!

**Comment by jasonmamy** [comment]
I would, but the pics never were attached, all I saw was:

I’ve found the problem. The theme you’re using has been introduced in
Android 5.1. For versions before 5.1, it falls back to default themes.
Those two changes fix the behavior in all Android versions.

[cid:image002.png@01D3A963.A081BD70]


[cid:image001.png@01D3A963.30C1F3B0]

I’ve also been facing some problems with JS code in selectorplugin.js in
the context of a Cordova app. I had to change the following lines:

[cid:image003.png@01D3A964.0BE44790]

**Comment by hohae** [comment]
Hi,

please find attached my current code. It works but is not yet production quality – therefore no PR yet from me.

Regards,
Holger

**Comment by isaqib23** [comment]
**I solved this issue by changing android app theme. see**

![screenshot_2018-08-30-18-10-42](https://user-images.githubusercontent.com/15919606/44854698-b65bde00-ac82-11e8-8891-bb0b7461690c.png)


**Follow these steps for changing android app theme:**
1. go to **your-project\platforms\android\app\src\main\AndroidManifest.xml**
2. find **@android:style/Theme.DeviceDefault.NoActionBar** & change this with **@android:style/Theme.Material.Light.NoActionBar**
3. re-generate your apk file
