### ISSUE TITLE
Browser compatibility

### ISSUE THREAD

**Issue by Ikito10** [jasonmamy/cordova-wheel-selector-plugin#22]
Hi,

I can only dev by building the .apk on a real device and it takes a really long time to build (about 2-3 mins). Is there any way to use it on browser via cordova maybe ?

**Comment by jasonmamy** [comment]
If it were to run in a browser it would use html select widgets and not the
native code, so the only way to see your changes to the android/java code
is to rebuild it, it is a painful process!
