### ISSUE TITLE
Animation is too slow

### ISSUE THREAD

**Issue by firegnome** [jasonmamy/cordova-wheel-selector-plugin#26]
Hey guys

Thank you for your awesome plugin, you did a fantastic job! I included the selector in my app and i recognized, that the animation speed is very slow. I compared it to the DatePicker plugin and saw that they used the animation speed 0.3 and you are using 0.5 which feels unnaturally slow. As far as i can see this is statically programmed and can't be configured within the plugin.

DatePicker code: https://github.com/VitaliiBlagodir/cordova-plugin-datepicker/blob/bd87605936b450dc32de0cddfb2ddb4936803fe0/src/ios/DatePicker.m#L33

WheelSelector code: https://github.com/jasonmamy/cordova-wheel-selector-plugin/blob/master/src/ios/SelectorCordovaPlugin.m#L195

If you share my opinion on this topic i would propose to change the animation speed to 0.3 or add a configuration for this.

I'm looking forward to hear from you!

**Comment by jasonmamy** [comment]
Yea if you can create a pull request, I'd gladly merge and push out a new
release
