### ISSUE TITLE
Ionic required to work?

### ISSUE THREAD

**Issue by JoshuaPerk** [jasonmamy/cordova-wheel-selector-plugin#28]
I can't determine based on the documentation if this plugin works _with_ Ionic or _requires_ it. I'm simply running Onsen UI and a jQuery framework. When building on iOS (both emulator and device), no errors are thrown when calling the plugin, but it simply doesn't do anything.

**Comment by jasonmamy** [comment]
This plugin is designed to use ionic in how ionic calls native code
(cordova).  Look up using apache cordova, might shed more insight if you
can use it, as this plugin as all ionic plugins are based on cordova.

**Comment by JoshuaPerk** [comment]
@jasonmamy, you're correct. I was able to get the underlying Cordova framework to work and now it appears it's communicating with the native OS.

On a separate note, my items are not loading using the example data/code.
![image](https://user-images.githubusercontent.com/26745245/39675946-f3f502d6-512f-11e8-82f4-8f15910b0d41.png)

**Comment by jasonmamy** [comment]
What does your code look like?
