### ISSUE TITLE
Default value is needed

### ISSUE THREAD

**Issue by fhoriuchi** [jasonmamy/cordova-wheel-selector-plugin#3]
Please add a functionality that default value (Selected value) can be set

**Comment by jasonmamy** [comment]
I added default value for Android (see version 1.0.4).  Will add to iOS in
future release.

See usage options:

https://github.com/jasonmamy/cordova-wheel-selector-plugin#the-options-that-can-be-set

**Comment by fhoriuchi** [comment]
Thanks!

**Comment by xatshepsut** [comment]
Hi,
I've already implemented that capability for iOS on my fork. 
Submitted a pull request with my changes ->  #4

**Comment by jasonmamy** [comment]
Awesome!  I just merged it, do you want me to spin off another release to
npm (1.0.5) where we can all test it?

**Comment by jasonmamy** [comment]
Ok, 1.0.5 is out there, figure we'll go to 2.0 in the next release - I'm
working on pushing it into @ionic-native for ionic v2.0.

**Comment by xatshepsut** [comment]
My changes are QA tested, iOS only.

**Comment by xatshepsut** [comment]
Will Ionic 2 support be backward compatible?
Btw, what's the procedure of closing issues? Should we pass specific test cases?

**Comment by xatshepsut** [comment]
@jasonmamy I just noticed we use different options for this. Android uses defaultValueIndexes with indexes, iOS uses defaultItems with actual values that it tries to match from list of values (I found this more intuitive in my project).
What do you think, should we handle both on both platforms?

**Comment by jasonmamy** [comment]
For closing issues, yea probably do some sort of a test (maybe in the
example app) to verify it?  I've been adding in new buttons in the
index.html that kinda 'cover' the functionality.  These plugins seem
extremely difficult to automate testing, probably more hassle than it's
worth.

defaultItems - make perfect sense, I just commited changes that took out
the defaultIndex stuff and uses the defaultItems on android (so now
iOS/Android are the same), so we don't have to maintain separate
items/index stuff.

for Ionic2, yea it's totally backward compatible, from what I'm seeing, we
don't even modify anything, it's more of a packaging thing for Ionic2 as
they handle plugins slightly different (actually in a much better way than
v1).

Thanks!
