### ISSUE TITLE
 WARN: Native: tried calling WheelSelector.show, but the WheelSelector plugin is not installed.

### ISSUE THREAD

**Issue by nasy** [jasonmamy/cordova-wheel-selector-plugin#33]
I am having some issues with this plugin.

I followed the steps to install the plugin listed in the main page for Ionic 2  
https://ionicframework.com/docs/native/wheelselector-plugin/

My config.xml has it installed:
<plugin name="cordova-wheel-selector-plugin" spec="~1.0.0" />

And in my my package.json also:
"@ionic-native/wheel-selector": "4.9.0"

And in app.module:
providers: [
...
    WheelSelector
  ],

If I do:
cordova plugin list the plugin is there
cordova-wheel-selector-plugin 1.0.0 "Cordova Wheel Selector Plugin"

However when I try to run the wheel on emulator (IOS Iphone 8, v 9.0) I get:

WARN: Native: tried calling WheelSelector.show, but the WheelSelector plugin is not installed.

**So it's is installed but the app doesn't seem to agree, any ideas what can be wrong?**

> 
> 
> Dependecies:
> 
>  "dependencies": {
>         "@angular/animations": "4.3.6",
>         "@angular/common": "4.3.6",
>         "@angular/compiler": "4.3.6",
>         "@angular/compiler-cli": "4.3.6",
>         "@angular/core": "4.3.6",
>         "@angular/forms": "4.3.6",
>         "@angular/http": "4.3.6",
>         "@angular/platform-browser": "4.3.6",
>         "@angular/platform-browser-dynamic": "4.3.6",
>         "@angular/router": "4.3.6",
>         "@ionic-native/barcode-scanner": "4.7.0",
>         "@ionic-native/core": "4.9.0",
>         "@ionic-native/file": "4.1.0",
>         "@ionic-native/network": "4.4.2",
>         "@ionic-native/printer": "3.12.1",
>         "@ionic-native/social-sharing": "3.14.0",
>         "@ionic-native/splash-screen": "3.4.2",
>         "@ionic-native/status-bar": "3.4.2",
>         "@ionic-native/wheel-selector": "4.9.0",
>         "@ionic/storage": "2.0.1",
>         "angular-in-memory-web-api": "0.3.0",
>         "compass-sass-mixins": "0.12.7",
>         "cordova-android": "6.2.3",
>         "cordova-ios": "4.4.0",
>         "cordova-plugin-add-swift-support": "1.7.0",
>         "cordova-plugin-console": "1.0.5",
>         "cordova-plugin-device": "1.1.4",
>         "cordova-plugin-file": "4.3.3",
>         "cordova-plugin-ionic": "2.0.3",
>         "cordova-plugin-network-information": "1.3.4",
>         "cordova-plugin-splashscreen": "4.0.1",
>         "cordova-plugin-statusbar": "2.2.3",
>         "cordova-plugin-whitelist": "1.3.1",
>         "cordova-plugin-x-socialsharing": "5.1.8",
>         "core-js": "2.4.1",
>         "de.appplant.cordova.plugin.printer": "0.7.1",
>         "exceptionless": "1.5.4",
>         "ionic-angular": "3.6.0",
>         "ionic-plugin-keyboard": "2.2.1",
>         "ionicons": "3.0.0",
>         "jwt-decode": "2.2.0",
>         "ng2-pdf-viewer": "2.0.1",
>         "ngx-toastr": "6.5.0",
>         "phonegap-plugin-barcodescanner": "7.0.4",
>         "rxjs": "5.1.1",
>         "sw-toolbox": "3.4.0",
>         "systemjs": "0.19.40",
>         "zone.js": "0.8.4"
>     }
> 
> 
>

**Comment by jasonmamy** [comment]
Can you try on an actual device to see if that works?

**Comment by nasy** [comment]
Hi @jasonmamy , yes I just tried on an IOS device (Iphone 7)  IOS 11.4. 

Same thing as in the emulator ¯\_(ツ)_/¯

**Comment by nasy** [comment]
It turns out the problem was caused due to a mismatch with some dependency versions, that for some strange reasons were different in the config.xml and the package.json. After fixing that the plugin started working. Sorry for the confusion, I am closing this one.

**Comment by mlembke1** [comment]
Hello @nasy,

I am having the exact same issue as you. I check the `config.xml` and `package.json`. Sure enough, they were different versions. However, after fixing them, I am still getting the same error.

<img width="1061" alt="screen shot 2018-07-11 at 6 28 09 am" src="https://user-images.githubusercontent.com/24907934/42571197-a4a3fc82-84d3-11e8-9f91-3f1aaefa68e5.png">
<img width="386" alt="screen shot 2018-07-11 at 6 27 59 am" src="https://user-images.githubusercontent.com/24907934/42571198-a4b7b592-84d3-11e8-853d-4834370003d1.png">
<img width="362" alt="screen shot 2018-07-11 at 6 27 48 am" src="https://user-images.githubusercontent.com/24907934/42571199-a4caab5c-84d3-11e8-83ba-9ceba85cfaac.png">
<img width="656" alt="screen shot 2018-07-11 at 6 27 14 am" src="https://user-images.githubusercontent.com/24907934/42571201-a4dbec78-84d3-11e8-9204-7611f4204b66.png">


I was wondering if you could give me some advice! Thanks!

**Comment by nasy** [comment]
<img width="649" alt="screen shot 2018-07-11 at 15 00 08" src="https://user-images.githubusercontent.com/2955118/42573091-71fbfbf2-851b-11e8-8f11-75d877302644.png">
<img width="934" alt="screen shot 2018-07-11 at 15 00 44" src="https://user-images.githubusercontent.com/2955118/42573092-7217cdfa-851b-11e8-8408-fbe226682af0.png">

The problem got fixed by making sure the config.xml and package.json had the same versions. Also updating to ios last version, and reinstalling all the plugins. Not sure if this helps much but I think your problem has to be around there. ¯_(ツ)_/¯

**Comment by mlembke1** [comment]
@nasy Awesome! Thanks for the quick reply. I'll give it a shot.

**Comment by mlembke1** [comment]
Hello @jasonmamy, 
I am hoping that you would be able to point me in the correct direction here. I do not want to open a new issue since I am having the same issue that @nasy had.


 I have changed the versions of the wheel selector to `1.0.0` in the following files
`package.json`
`package-lock.json`
`config.xml`
`node_modules/@ionic-native/wheel-selector/package.json`

BEFORE I switched the wheel selector version to `1.0.0` in the files above, the version was `4.9.1`.
I am still getting the error message

`[08:09:34]  console.warn: Native: tried calling WheelSelector.show, but the WheelSelector plugin is not installed. 
[08:09:34]  console.warn: Install the WheelSelector plugin: 'ionic cordova plugin add cordova-wheel-selector-plugin' 
[08:09:34]  console.log: Error: "plugin_not_installed" `

**Comment by jasonmamy** [comment]
Can you try using the current version 1.1.1:

https://github.com/jasonmamy/cordova-wheel-selector-plugin/blob/master/package.json

**Comment by mlembke1** [comment]
@jasonmamy Bummer. Looks like I cannot get it to work. 
No worries. I think I am going to try to use `https://github.com/raychenfj/ion-multi-picker` and see if I have any luck with that one. I appreciate your responsiveness!

**Comment by jasonmamy** [comment]
One thing you could try is with a fresh blank project:

ionic start TestWheelSelector blank
cd TestWheelSelector
ionic cordova plugin add cordova-wheel-selector-plugin
npm install --save @ionic-native/wheel-selector

And add a button to display the wheel selector in the home.ts/home.html
files.  At that point you can see the version(s) of all the different
libraries in the package.json and config.xml and compare.

**Comment by MrDrProfX** [comment]
For me, I just removed and added the platform and it worked again.
`ionic cordova platform remove ios`
`ionic cordova platform add ios`
