### ISSUE TITLE
How do I change the black background color around popup?

### ISSUE THREAD

**Issue by perpetual-claudius** [jasonmamy/cordova-wheel-selector-plugin#35]
Hi,

Using below line We changed the background from transparent to black. But I can't change the background color to grey. Kindly help us to change background color.

alert.getWindow().setDimAmount(1);

![background_black](https://user-images.githubusercontent.com/4033956/44395175-b9562080-a556-11e8-9f09-908ef6818025.png)

**Comment by jasonmamy** [comment]
Did you try a different value for the dimAmount?  Maybe .5 or .6?
