### ISSUE TITLE
Example #1 wrong syntax

### ISSUE THREAD

**Issue by josh-yates** [jasonmamy/cordova-wheel-selector-plugin#42]
Thanks for this plugin, it works very smoothly. I noticed an issue with example 1 in the docs (Single items, white theme) that caused a bit of confusion - data.numbers should be [data.numbers]

**Comment by jasonmamy** [comment]
Thanks, fixed.

**Comment by josh-yates** [comment]
Sorry I think you misunderstood me with the fix in https://github.com/jasonmamy/cordova-wheel-selector-plugin/commit/a3d0dd495585c76df3f02e8e10b18017c7cecd44 . The syntax should be:
`items: [[data.numbers]]` so each of the examples should have that extra pair of square brackets

**Comment by jasonmamy** [comment]
Ok, thanks, fixed

**Comment by josh-yates** [comment]
Looks good to me, thanks for taking time to fix this
