### ISSUE TITLE
Plugin should use a background thread. No show wheel elements

### ISSUE THREAD

**Issue by Bezlepkin** [jasonmamy/cordova-wheel-selector-plugin#46]
On a new installation Cordova,  i have a bug (IOS):
THREAD WARNING: ['SelectorCordovaPlugin'] took '41.500732' ms. Plugin should use a background thread.
![2019-01-30_22-29-30](https://user-images.githubusercontent.com/10475699/52011726-d9b4de80-24e9-11e9-8283-266a6af6cbcc.png)

**Comment by jasonmamy** [comment]
What version of the plugin and ionic are you using? The current plugin
version is 1.1.2, possibly try to roll it back to 1.1.1?

**Comment by Bezlepkin** [comment]
I use without Ionic.
Try 1.1.1, still:
THREAD WARNING: ['SelectorCordovaPlugin'] took '98.888184' ms. Plugin should use a background thread. 
and empty wheel

**Comment by Bezlepkin** [comment]
-

**Comment by jasonmamy** [comment]
This can't be reproduced as there's no framework being used, no details, and no code.
