### ISSUE TITLE
Compilation error due to current examples folder

### ISSUE THREAD

**Issue by hoangdung-nguyen-6791** [jasonmamy/cordova-wheel-selector-plugin#51]
Although PR #50 has been merged, it did not seem to take effect. Please consider triggering a new package build and release (possibly 1.0.2) which actually exclude the `examples` folder after all. Many thanks, @jasonmamy.

**Comment by jasonmamy** [comment]
I did a clean sync from github (deleted my local dir), revved new version
to 1.1.3.
Ran npm pack and verified that there were no examples in the published
package (the .npmignore file contains /examples). See if this helps.

**Comment by hoangdung-nguyen-6791** [comment]
Thanks, @jasonmamy. I've just checked and it's vanished for now.
