### ISSUE TITLE
Text not showing up on android 10

### ISSUE THREAD

**Issue by zheng17** [jasonmamy/cordova-wheel-selector-plugin#56]
![image](https://user-images.githubusercontent.com/25708672/74787825-c05a0e00-5275-11ea-8d88-a1d3eb38999a.png)
Failed to set text color in Android 10 Devices. 

I fork the branch and made one quick fix, please merge that.

https://github.com/zheng17/cordova-wheel-selector-plugin/commit/80c1ecb69fc22ea7148f8d6a615eea605fdfe9ae#diff-8bc41c3962ff62f78ac188b0c90cb9c6

**Comment by jasonmamy** [comment]
Great! Do you think you could create a 'pull request' so I can merge it
seamlessly into the code base?

Thanks, Jason

**Comment by zheng17** [comment]
The pull request has been submitted. Thanks.

**Comment by jasonmamy** [comment]
Thanks, everything is updated (new release 1.1.5) and published to npm.
